### DATA MANIPULATION / DATA CLEANING

### DATA MANIPULATION / DATA CLEANING

### DATA MANIPULATION / DATA CLEANING

#### My own note . 
- I can use this for my research work Data Analysis
- You must also understand your data you are working with

In [4]:
### import library
import pandas as pd
import numpy as np

In [5]:
### Import our dataset into pandas
agric_data = pd.read_csv("agric.csv")

In [6]:

### Display the top rows
agric_data.head() ## by default it will give you the first five but you can also be specific by input your prefered number say(9)
## if you want the last row too you can say agric_data.tail() same rule above applies.

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356
4,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149

In [7]:
### check for number of rows in the table
print(f"The number of rows is {len(agric_data)}")

### check for number of columns in the table
print(f"The number od columns is {len(agric_data.columns)}")

The number of rows is 13961
The number od columns is 9

In [8]:
#### check for the rows and columns
agric_data.shape

(13961, 9)

In [9]:
### check for columns
agric_data.columns

Index(['Record_ID', 'Date', 'Region', 'Crop', 'Rainfall_mm', 'Yield_kg',
       'Price_GHS', 'Temperature_C', 'Farmer_Count'],
      dtype='object')

In [10]:
### check for basic information about the table
agric_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13961 entries, 0 to 13960
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Record_ID      13961 non-null  int64
 1   Date           13961 non-null  object
 2   Region         13961 non-null  object
 3   Crop           13961 non-null  object
 4   Rainfall_mm    13822 non-null  float64
 5   Yield_kg       13822 non-null  float64
 6   Price_GHS      13821 non-null  float64
 7   Temperature_C  13961 non-null  float64
 8   Farmer_Count   13961 non-null  int64
dtypes: float64(4), int64(2), object(3)
memory usage: 981.8+ KB

In [11]:
### checking for data types
agric_data.dtypes

Record_ID          int64
Date              object
Region            object
Crop              object
Rainfall_mm      float64
Yield_kg         float64
Price_GHS        float64
Temperature_C    float64
Farmer_Count       int64
dtype: object

In [12]:
### surrogate keys in your dataset, eg is using identification numbers
### primary keys

### Missing values

In [13]:
### checking for missing values ('agric_data.isnull()')
agric_data.isnull().sum() ### return the number of missing valuees

Record_ID          0
Date               0
Region             0
Crop               0
Rainfall_mm      139
Yield_kg         139
Price_GHS        140
Temperature_C      0
Farmer_Count       0
dtype: int64

In [14]:
### Or  also used for checking missing values
agric_data.isna()

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
13956,False,False,False,False,False,False,False,False,False
13957,False,False,False,False,False,False,False,False,False
13958,False,False,False,False,False,False,False,False,False
13959,False,False,False,False,False,False,False,False,False
13960,False,False,False,False,False,False,False,False,False

In [15]:
agric_data.isna().sum().sum() ## this is given as the total of missing values

np.int64(418)

In [16]:
### checking for the percentage of missing values
percent_missing_value = (agric_data.isnull().sum()/len(agric_data)*100).round(3)

In [17]:
### Extract the columns
percent_missing_value > 0.5

Record_ID        False
Date             False
Region           False
Crop             False
Rainfall_mm       True
Yield_kg          True
Price_GHS         True
Temperature_C    False
Farmer_Count     False
dtype: bool

In [18]:
 ## checking for columns with more than o.5% missing values
percent_missing_value[percent_missing_value>0.5]

Rainfall_mm    0.996
Yield_kg       0.996
Price_GHS      1.003
dtype: float64

### Replce Missing Values

In [19]:
### Decision is that for columns with missing values we replace them with zeros
agric_data["Rainfall_mm"]=agric_data["Rainfall_mm"].fillna(0)

In [20]:
agric_data["Yield_kg"]=agric_data["Yield_kg"].fillna(0)

In [21]:
agric_data["Price_GHS"]=agric_data["Price_GHS"].fillna(0)

In [22]:
### confirm missing values has been filled
agric_data.isnull().sum()

Record_ID        0
Date             0
Region           0
Crop             0
Rainfall_mm      0
Yield_kg         0
Price_GHS        0
Temperature_C    0
Farmer_Count     0
dtype: int64

### Duplicates

In [23]:
### checking for duplicates
agric_data.duplicated() ## considers the entire row to flag duplicate

0        False
1        False
2        False
3        False
4         True
         ...
13956    False
13957    False
13958    False
13959    False
13960    False
Length: 13961, dtype: bool

In [24]:
agric_data[agric_data.duplicated()]

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
4,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
16,7,2021-01-01,Northern,Cassava,0.00,0.00,1.05,28.0,319
38,30,2021-01-03,Ashanti,Maize,0.00,1369.96,1.96,27.7,441
56,48,2021-01-04,Northern,Cassava,0.13,0.00,1.23,26.6,443
59,50,2021-01-04,Western,Maize,12.34,0.00,2.29,25.3,494
61,38,2021-01-03,Western,Cocoa,3.71,0.00,10.12,30.1,365

In [25]:
### checking for duplicate using a specific column
agric_data.duplicated(subset="Record_ID") ### record_id as the primary key

0        False
1        False
2        False
3        False
4         True
         ...
13956    False
13957    False
13958    False
13959    False
13960    False
Length: 13961, dtype: bool

In [26]:
### Removing duplicate
agric_data.drop_duplicates()

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356
5,5,2021-01-01,Ashanti,Cocoa,0.00,230.60,10.06,30.8,477
...,...,...,...,...,...,...,...,...,...
13956,13951,2023-12-31,Western,Cassava,3.02,9608.61,1.37,26.0,297
13957,13952,2023-12-31,Western,Cocoa,8.38,0.00,14.34,31.8,174
13958,13953,2023-12-31,Eastern,Maize,1.25,0.00,2.16,28.0,170
13959,13954,2023-12-31,Eastern,Cassava,0.32,6288.00,1.33,26.0,423
13960,13955,2023-12-31,Eastern,Cocoa,4.24,0.00,14.70,30.9,152

In [27]:

agric_data.drop_duplicates(inplace=True)

In [28]:
### check the shape of the new dataset
agric_data.shape

(13955, 9)

### Statistical Summaries

In [29]:
agric_data.describe() ## gives a summary on the numeric entities

,Record_ID,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
count,13955.000000,13955.000000,13955.000000,13955.000000,13955.000000,13955.000000
mean,6978.000000,13.859529,428.861775,5.693415,28.975973,273.055607
std,4028.605838,12.182697,1824.482132,5.525272,2.879893,130.533755
min,1.000000,0.000000,0.000000,0.000000,24.000000,50.000000
25%,3489.500000,4.245000,0.000000,1.390000,26.500000,159.000000
50%,6978.000000,10.240000,0.000000,2.620000,29.000000,272.000000
75%,10466.500000,21.440000,0.000000,11.830000,31.500000,386.000000
max,13955.000000,57.690000,21666.200000,18.220000,34.000000,499.000000

In [30]:
### Statistical summary on price

agric_data["Price_GHS"].describe()

count    13955.000000
mean         5.693415
std          5.525272
min          0.000000
25%          1.390000
50%          2.620000
75%         11.830000
max         18.220000
Name: Price_GHS, dtype: float64

In [31]:
### Statistical summary for object data type
agric_data.describe(include="object")

              Date   Region     Crop
count        13955    13955    13955
unique        1095        5        3
top     2023-12-31  Western  Cassava
freq            15     2807     4673

In [32]:
agric_data["Crop"].mode() ### Checking for most appearing
### This not really part of the cleaning unless necessary

0    Cassava
Name: Crop, dtype: object

### Unique values

In [33]:
### Return unique values on all columns

agric_data.nunique()

Record_ID        13955
Date              1095
Region               5
Crop                 3
Rainfall_mm       3947
Yield_kg          1674
Price_GHS         1129
Temperature_C      101
Farmer_Count       450
dtype: int64

In [34]:
### Return the unique elements in a Region

agric_data["Region"].unique()

array(['Greater Accra', 'Ashanti', 'Northern', 'Western', 'Eastern'],
      dtype=object)

In [35]:
agric_data["Price_GHS"].unique()

array([ 1.86, 13.02,  1.92, ..., 17.73, 17.86, 10.89], shape=(1129,))

In [36]:
### check for number unique elements and the element itself

agric_data["Region"].value_counts()

Region
Western          2807
Eastern          2806
Greater Accra    2798
Ashanti          2789
Northern         2755
Name: count, dtype: int64

### Selecting Columns

In [37]:
agric_data.select_dtypes(include="number") ### just selecting numerical datatypes

,Record_ID,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,7.27,1139.48,1.86,32.7,149
1,2,4.88,0.00,13.02,24.0,493
2,3,0.00,1467.28,1.92,26.9,320
3,4,10.39,10511.46,1.11,24.5,356
5,5,0.00,230.60,10.06,30.8,477
...,...,...,...,...,...,...
13956,13951,3.02,9608.61,1.37,26.0,297
13957,13952,8.38,0.00,14.34,31.8,174
13958,13953,1.25,0.00,2.16,28.0,170
13959,13954,0.32,6288.00,1.33,26.0,423
13960,13955,4.24,0.00,14.70,30.9,152

In [38]:
agric_data.select_dtypes(include="object") ### just selecting objects datatypes

             Date         Region     Crop
0      2021-01-01  Greater Accra    Maize
1      2021-01-01  Greater Accra    Cocoa
2      2021-01-01        Ashanti    Maize
3      2021-01-01        Ashanti  Cassava
5      2021-01-01        Ashanti    Cocoa
...           ...            ...      ...
13956  2023-12-31        Western  Cassava
13957  2023-12-31        Western    Cocoa
13958  2023-12-31        Eastern    Maize
13959  2023-12-31        Eastern  Cassava
13960  2023-12-31        Eastern    Cocoa

[13955 rows x 3 columns]

In [39]:
agric_data.head(2)

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493

In [40]:
### Replacing an item using iloc  ## changing maize to wheat
agric_data.iloc[0,3] = "wheat"

In [41]:
agric_data.head(2)

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,wheat,7.27,1139.48,1.86,32.7,149
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493

In [42]:

### changing  wheat to maize
agric_data.loc[0,"Crop"]="Maize"

In [43]:
agric_data.head()

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356
5,5,2021-01-01,Ashanti,Cocoa,0.00,230.60,10.06,30.8,477

### Masking/Filtering

In [44]:
### Volume of rainfall more than 30mm

agric_data[agric_data["Rainfall_mm"]>30]

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
1148,1143,2021-04-01,Ashanti,Cocoa,30.67,0.00,12.65,25.3,272
1156,1151,2021-04-01,Eastern,Cocoa,30.56,0.00,14.98,24.2,417
1164,1159,2021-04-02,Western,Maize,51.09,0.00,2.44,30.3,419
1165,1160,2021-04-02,Western,Cassava,41.89,0.00,1.10,32.2,246
1166,1161,2021-04-02,Western,Cocoa,51.30,0.00,0.00,27.5,494
...,...,...,...,...,...,...,...,...,...
13127,13122,2023-10-30,Ashanti,Cassava,33.33,15287.95,1.13,27.6,134
13134,13129,2023-10-30,Western,Cocoa,31.69,0.00,11.37,28.5,356
13148,13143,2023-10-31,Western,Cassava,34.09,0.00,1.16,26.0,219
13149,13144,2023-10-31,Western,Cocoa,52.76,0.00,12.27,31.1,173
13150,13145,2023-10-31,Eastern,Maize,35.05,0.00,2.62,24.2,200

In [45]:
### We want to obtain the yield for maize crop and the yield by "Masking"
agric_data[agric_data["Crop"]=="Maize"]

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320
6,6,2021-01-01,Northern,Maize,3.58,0.00,2.03,30.6,51
9,9,2021-01-01,Western,Maize,1.87,1579.39,1.93,32.0,114
11,11,2021-01-01,Eastern,Maize,0.00,0.00,2.34,27.3,97
...,...,...,...,...,...,...,...,...,...
13946,13941,2023-12-31,Greater Accra,Maize,8.07,0.00,2.43,30.9,94
13949,13944,2023-12-31,Ashanti,Maize,0.00,1712.52,2.84,29.5,453
13952,13947,2023-12-31,Northern,Maize,3.12,0.00,2.91,26.2,86
13955,13950,2023-12-31,Western,Maize,5.03,0.00,2.95,30.0,212
13958,13953,2023-12-31,Eastern,Maize,1.25,0.00,2.16,28.0,170

In [46]:
### Using loc

agric_data.loc[agric_data["Crop"]=="Maize",["Crop","Yield_kg"]]

        Crop  Yield_kg
0      Maize   1139.48
2      Maize   1467.28
6      Maize      0.00
9      Maize   1579.39
11     Maize      0.00
...      ...       ...
13946  Maize      0.00
13949  Maize   1712.52
13952  Maize      0.00
13955  Maize      0.00
13958  Maize      0.00

[4646 rows x 2 columns]

In [47]:
### we want to return maize and cassava
agric_data[(agric_data["Crop"]=="Maize")|(agric_data["Crop"]=="Cassava")]

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356
6,6,2021-01-01,Northern,Maize,3.58,0.00,2.03,30.6,51
7,7,2021-01-01,Northern,Cassava,0.00,0.00,1.05,28.0,319
...,...,...,...,...,...,...,...,...,...
13953,13948,2023-12-31,Northern,Cassava,1.72,0.00,1.14,27.3,329
13955,13950,2023-12-31,Western,Maize,5.03,0.00,2.95,30.0,212
13956,13951,2023-12-31,Western,Cassava,3.02,9608.61,1.37,26.0,297
13958,13953,2023-12-31,Eastern,Maize,1.25,0.00,2.16,28.0,170
13959,13954,2023-12-31,Eastern,Cassava,0.32,6288.00,1.33,26.0,423

In [48]:
agric_data.loc[(agric_data["Crop"]=="Maize")|(agric_data["Crop"]=="Cassava"),["Crop","Yield_kg"]].head(2)

    Crop  Yield_kg
0  Maize   1139.48
2  Maize   1467.28

##isin Method

In [49]:
### we want to return the yield for maize and cassava
agric_data.loc[agric_data["Crop"].isin(["Maize","Cassava"]),["Crop","Yield_kg"]]

          Crop  Yield_kg
0        Maize   1139.48
2        Maize   1467.28
3      Cassava  10511.46
6        Maize      0.00
7      Cassava      0.00
...        ...       ...
13953  Cassava      0.00
13955    Maize      0.00
13956  Cassava   9608.61
13958    Maize      0.00
13959  Cassava   6288.00

[9319 rows x 2 columns]

In [50]:
### Extract crops (maize,cassava) that were sold within the range of 1-2 cedis
agric_data.loc[(agric_data["Crop"].isin(["Cassava","Maize"])& (agric_data["Price_GHS"].between(1,2)))]

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356
7,7,2021-01-01,Northern,Cassava,0.00,0.00,1.05,28.0,319
9,9,2021-01-01,Western,Maize,1.87,1579.39,1.93,32.0,114
...,...,...,...,...,...,...,...,...,...
13947,13942,2023-12-31,Greater Accra,Cassava,1.72,0.00,1.16,32.0,252
13950,13945,2023-12-31,Ashanti,Cassava,13.96,0.00,1.23,28.4,117
13953,13948,2023-12-31,Northern,Cassava,1.72,0.00,1.14,27.3,329
13956,13951,2023-12-31,Western,Cassava,3.02,9608.61,1.37,26.0,297
13959,13954,2023-12-31,Eastern,Cassava,0.32,6288.00,1.33,26.0,423

### query method

In [51]:
### we want to extract maize or cassava
agric_data.query("Crop=='Maize'or Crop=='Cassava'")
agric_data.query("Crop in ['Maize','Cassava']")

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356
6,6,2021-01-01,Northern,Maize,3.58,0.00,2.03,30.6,51
7,7,2021-01-01,Northern,Cassava,0.00,0.00,1.05,28.0,319
...,...,...,...,...,...,...,...,...,...
13953,13948,2023-12-31,Northern,Cassava,1.72,0.00,1.14,27.3,329
13955,13950,2023-12-31,Western,Maize,5.03,0.00,2.95,30.0,212
13956,13951,2023-12-31,Western,Cassava,3.02,9608.61,1.37,26.0,297
13958,13953,2023-12-31,Eastern,Maize,1.25,0.00,2.16,28.0,170
13959,13954,2023-12-31,Eastern,Cassava,0.32,6288.00,1.33,26.0,423

### String Method

In [52]:
### check if the region stated contains "Western"
agric_data["Region"].str.contains("Western",case=False)

0        False
1        False
2        False
3        False
5        False
         ...
13956     True
13957     True
13958    False
13959    False
13960    False
Name: Region, Length: 13955, dtype: bool

### Sorting

In [53]:
### we want to know the rainfall volume in a decreasing order
agric_data["Rainfall_mm"].sort_values(ascending=False)

1754    57.69
3591    57.57
2021    56.60
7893    56.53
8329    56.52
        ...
3990     0.00
3993     0.00
7542     0.00
4004     0.00
4056     0.00
Name: Rainfall_mm, Length: 13955, dtype: float64

In [54]:
agric_data.sort_values("Rainfall_mm",ascending=False)

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count
1754,1749,2021-05-18,Western,Cassava,57.69,0.00,1.11,30.1,120
3591,3586,2021-10-10,Western,Cocoa,57.57,484.69,9.88,26.2,261
2021,2016,2021-06-08,Western,Maize,56.60,0.00,2.40,30.9,377
7893,7888,2022-09-13,Western,Maize,56.53,0.00,2.90,26.1,101
8329,8324,2022-10-16,Western,Cassava,56.52,12439.39,1.23,25.6,407
...,...,...,...,...,...,...,...,...,...
3990,3985,2021-11-10,Greater Accra,Cocoa,0.00,278.83,12.83,25.1,106
3993,3988,2021-11-10,Northern,Maize,0.00,0.00,1.88,26.9,385
7542,7537,2022-08-16,Western,Cassava,0.00,0.00,1.40,26.2,102
4004,3999,2021-11-11,Northern,Maize,0.00,0.00,2.20,28.9,165
4056,4051,2021-11-15,Northern,Cocoa,0.00,193.10,13.19,27.5,160

### Sort on Multiple Column

In [55]:
### sort in terms of farmers and the yield
agric_data[["Farmer_Count","Yield_kg"]].sort_values(by=["Farmer_Count","Yield_kg"],ascending=[False,True])

       Farmer_Count  Yield_kg
75              499      0.00
237             499      0.00
562             499      0.00
839             499      0.00
840             499      0.00
...             ...       ...
13631            50      0.00
4462             50   1427.56
13058            50   1888.85
5224             50   6089.61
9096             50   7641.01

[13955 rows x 2 columns]

In [56]:
agric_data.sort_values

<bound method DataFrame.sort_values of        Record_ID        Date         Region     Crop  Rainfall_mm  Yield_kg  \
0              1  2021-01-01  Greater Accra    Maize         7.27   1139.48
1              2  2021-01-01  Greater Accra    Cocoa         4.88      0.00
2              3  2021-01-01        Ashanti    Maize         0.00   1467.28
3              4  2021-01-01        Ashanti  Cassava        10.39  10511.46
5              5  2021-01-01        Ashanti    Cocoa         0.00    230.60
...          ...         ...            ...      ...          ...       ...
13956      13951  2023-12-31        Western  Cassava         3.02   9608.61
13957      13952  2023-12-31        Western    Cocoa         8.38      0.00
13958      13953  2023-12-31        Eastern    Maize         1.25      0.00
13959      13954  2023-12-31        Eastern  Cassava         0.32   6288.00
13960      13955  2023-12-31        Eastern    Cocoa         4.24      0.00

       Price_GHS  Temperature_C  Farmer_Count
0           1.86           32.7           149
1          13.02           24.0           493
2           1.92           26.9           320
3           1.11           24.5           356
5          10.06           30.8           477
...          ...            ...           ...
13956       1.37           26.0           297
13957      14.34           31.8           174
13958       2.16           28.0           170
13959       1.33           26.0           423
13960      14.70           30.9           152

[13955 rows x 9 columns]>

### Adding Columns

In [57]:
## include the nationality of the farmers
agric_data['Country'] = 'Ghana'

In [58]:
agric_data

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Country
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149,Ghana
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493,Ghana
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320,Ghana
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356,Ghana
5,5,2021-01-01,Ashanti,Cocoa,0.00,230.60,10.06,30.8,477,Ghana
...,...,...,...,...,...,...,...,...,...,...
13956,13951,2023-12-31,Western,Cassava,3.02,9608.61,1.37,26.0,297,Ghana
13957,13952,2023-12-31,Western,Cocoa,8.38,0.00,14.34,31.8,174,Ghana
13958,13953,2023-12-31,Eastern,Maize,1.25,0.00,2.16,28.0,170,Ghana
13959,13954,2023-12-31,Eastern,Cassava,0.32,6288.00,1.33,26.0,423,Ghana
13960,13955,2023-12-31,Eastern,Cocoa,4.24,0.00,14.70,30.9,152,Ghana

In [59]:
agric_data["Revenue"]=agric_data["Yield_kg"]*agric_data["Price_GHS"]

In [60]:
agric_data["Revenue"]

0         2119.4328
1            0.0000
2         2817.1776
3        11667.7206
5         2319.8360
            ...
13956    13163.7957
13957        0.0000
13958        0.0000
13959     8363.0400
13960        0.0000
Name: Revenue, Length: 13955, dtype: float64

In [61]:
agric_data

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Country,Revenue
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149,Ghana,2119.4328
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493,Ghana,0.0000
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320,Ghana,2817.1776
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356,Ghana,11667.7206
5,5,2021-01-01,Ashanti,Cocoa,0.00,230.60,10.06,30.8,477,Ghana,2319.8360
...,...,...,...,...,...,...,...,...,...,...,...
13956,13951,2023-12-31,Western,Cassava,3.02,9608.61,1.37,26.0,297,Ghana,13163.7957
13957,13952,2023-12-31,Western,Cocoa,8.38,0.00,14.34,31.8,174,Ghana,0.0000
13958,13953,2023-12-31,Eastern,Maize,1.25,0.00,2.16,28.0,170,Ghana,0.0000
13959,13954,2023-12-31,Eastern,Cassava,0.32,6288.00,1.33,26.0,423,Ghana,8363.0400
13960,13955,2023-12-31,Eastern,Cocoa,4.24,0.00,14.70,30.9,152,Ghana,0.0000

### Using the np.where condition

In [62]:
### we want to add a column called "rainfall_group"
### we want to convert the rainfall values to a categorical scale
### if rainfall value is >30mm, "heavy rainfall"
### if rainfall is between 30-20mm "moderate"
### else, "low"

agric_data["Rainfall_group"]=np.where(agric_data["Rainfall_mm"]>30,"Heavy",
                                      np.where(agric_data["Rainfall_mm"]>=20,"moderate","low"))

In [63]:
agric_data[["Rainfall_mm","Rainfall_group"]]

       Rainfall_mm Rainfall_group
0             7.27            low
1             4.88            low
2             0.00            low
3            10.39            low
5             0.00            low
...            ...            ...
13956         3.02            low
13957         8.38            low
13958         1.25            low
13959         0.32            low
13960         4.24            low

[13955 rows x 2 columns]

In [64]:
agric_data.head()

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Country,Revenue,Rainfall_group
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149,Ghana,2119.4328,low
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493,Ghana,0.0000,low
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320,Ghana,2817.1776,low
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356,Ghana,11667.7206,low
5,5,2021-01-01,Ashanti,Cocoa,0.00,230.60,10.06,30.8,477,Ghana,2319.8360,low

In [65]:
### insert a new column on the 4th index
agric_data.insert(4, "add_column", 50)

In [66]:
agric_data

,Record_ID,Date,Region,Crop,add_column,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Country,Revenue,Rainfall_group
0,1,2021-01-01,Greater Accra,Maize,50,7.27,1139.48,1.86,32.7,149,Ghana,2119.4328,low
1,2,2021-01-01,Greater Accra,Cocoa,50,4.88,0.00,13.02,24.0,493,Ghana,0.0000,low
2,3,2021-01-01,Ashanti,Maize,50,0.00,1467.28,1.92,26.9,320,Ghana,2817.1776,low
3,4,2021-01-01,Ashanti,Cassava,50,10.39,10511.46,1.11,24.5,356,Ghana,11667.7206,low
5,5,2021-01-01,Ashanti,Cocoa,50,0.00,230.60,10.06,30.8,477,Ghana,2319.8360,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13956,13951,2023-12-31,Western,Cassava,50,3.02,9608.61,1.37,26.0,297,Ghana,13163.7957,low
13957,13952,2023-12-31,Western,Cocoa,50,8.38,0.00,14.34,31.8,174,Ghana,0.0000,low
13958,13953,2023-12-31,Eastern,Maize,50,1.25,0.00,2.16,28.0,170,Ghana,0.0000,low
13959,13954,2023-12-31,Eastern,Cassava,50,0.32,6288.00,1.33,26.0,423,Ghana,8363.0400,low
13960,13955,2023-12-31,Eastern,Cocoa,50,4.24,0.00,14.70,30.9,152,Ghana,0.0000,low

### Modifying an existing column

In [67]:
### we want to increase the  value of new column by 50

agric_data["add_column"] = agric_data["add_column"] + 50

In [68]:
agric_data

,Record_ID,Date,Region,Crop,add_column,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Country,Revenue,Rainfall_group
0,1,2021-01-01,Greater Accra,Maize,100,7.27,1139.48,1.86,32.7,149,Ghana,2119.4328,low
1,2,2021-01-01,Greater Accra,Cocoa,100,4.88,0.00,13.02,24.0,493,Ghana,0.0000,low
2,3,2021-01-01,Ashanti,Maize,100,0.00,1467.28,1.92,26.9,320,Ghana,2817.1776,low
3,4,2021-01-01,Ashanti,Cassava,100,10.39,10511.46,1.11,24.5,356,Ghana,11667.7206,low
5,5,2021-01-01,Ashanti,Cocoa,100,0.00,230.60,10.06,30.8,477,Ghana,2319.8360,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13956,13951,2023-12-31,Western,Cassava,100,3.02,9608.61,1.37,26.0,297,Ghana,13163.7957,low
13957,13952,2023-12-31,Western,Cocoa,100,8.38,0.00,14.34,31.8,174,Ghana,0.0000,low
13958,13953,2023-12-31,Eastern,Maize,100,1.25,0.00,2.16,28.0,170,Ghana,0.0000,low
13959,13954,2023-12-31,Eastern,Cassava,100,0.32,6288.00,1.33,26.0,423,Ghana,8363.0400,low
13960,13955,2023-12-31,Eastern,Cocoa,100,4.24,0.00,14.70,30.9,152,Ghana,0.0000,low

#### Renaming an existing columns

In [69]:
### changing the Country to Nationality,add_column to new_column

agric_data.rename(columns={"Country":"Nationality","add_column":"new_column"})

,Record_ID,Date,Region,Crop,new_column,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Nationality,Revenue,Rainfall_group
0,1,2021-01-01,Greater Accra,Maize,100,7.27,1139.48,1.86,32.7,149,Ghana,2119.4328,low
1,2,2021-01-01,Greater Accra,Cocoa,100,4.88,0.00,13.02,24.0,493,Ghana,0.0000,low
2,3,2021-01-01,Ashanti,Maize,100,0.00,1467.28,1.92,26.9,320,Ghana,2817.1776,low
3,4,2021-01-01,Ashanti,Cassava,100,10.39,10511.46,1.11,24.5,356,Ghana,11667.7206,low
5,5,2021-01-01,Ashanti,Cocoa,100,0.00,230.60,10.06,30.8,477,Ghana,2319.8360,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13956,13951,2023-12-31,Western,Cassava,100,3.02,9608.61,1.37,26.0,297,Ghana,13163.7957,low
13957,13952,2023-12-31,Western,Cocoa,100,8.38,0.00,14.34,31.8,174,Ghana,0.0000,low
13958,13953,2023-12-31,Eastern,Maize,100,1.25,0.00,2.16,28.0,170,Ghana,0.0000,low
13959,13954,2023-12-31,Eastern,Cassava,100,0.32,6288.00,1.33,26.0,423,Ghana,8363.0400,low
13960,13955,2023-12-31,Eastern,Cocoa,100,4.24,0.00,14.70,30.9,152,Ghana,0.0000,low

In [70]:
agric_data.rename(columns={"Country":"Nationality","add_column":"new_column"},inplace=True)

In [71]:
agric_data.columns

Index(['Record_ID', 'Date', 'Region', 'Crop', 'new_column', 'Rainfall_mm',
       'Yield_kg', 'Price_GHS', 'Temperature_C', 'Farmer_Count', 'Nationality',
       'Revenue', 'Rainfall_group'],
      dtype='object')

In [72]:
agric_data.head()

,Record_ID,Date,Region,Crop,new_column,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Nationality,Revenue,Rainfall_group
0,1,2021-01-01,Greater Accra,Maize,100,7.27,1139.48,1.86,32.7,149,Ghana,2119.4328,low
1,2,2021-01-01,Greater Accra,Cocoa,100,4.88,0.00,13.02,24.0,493,Ghana,0.0000,low
2,3,2021-01-01,Ashanti,Maize,100,0.00,1467.28,1.92,26.9,320,Ghana,2817.1776,low
3,4,2021-01-01,Ashanti,Cassava,100,10.39,10511.46,1.11,24.5,356,Ghana,11667.7206,low
5,5,2021-01-01,Ashanti,Cocoa,100,0.00,230.60,10.06,30.8,477,Ghana,2319.8360,low

### Replacing Values

In [73]:
### managing warnings
import warnings
warnings.filterwarnings(action="ignore")

In [74]:
#####
agric_data.loc[agric_data["Region"]=="Greater Accra","Region"]="Accra"

In [75]:
agric_data.head()

,Record_ID,Date,Region,Crop,new_column,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Nationality,Revenue,Rainfall_group
0,1,2021-01-01,Accra,Maize,100,7.27,1139.48,1.86,32.7,149,Ghana,2119.4328,low
1,2,2021-01-01,Accra,Cocoa,100,4.88,0.00,13.02,24.0,493,Ghana,0.0000,low
2,3,2021-01-01,Ashanti,Maize,100,0.00,1467.28,1.92,26.9,320,Ghana,2817.1776,low
3,4,2021-01-01,Ashanti,Cassava,100,10.39,10511.46,1.11,24.5,356,Ghana,11667.7206,low
5,5,2021-01-01,Ashanti,Cocoa,100,0.00,230.60,10.06,30.8,477,Ghana,2319.8360,low

In [76]:
agric_data["Region"]

0          Accra
1          Accra
2        Ashanti
3        Ashanti
5        Ashanti
          ...
13956    Western
13957    Western
13958    Eastern
13959    Eastern
13960    Eastern
Name: Region, Length: 13955, dtype: object

In [77]:
### using the replace method
### Replace Accra to Greater Accra

agric_data["Region"].replace({"Accra":"Greater Accra"},inplace =True)

In [78]:
agric_data["Region"]

0        Greater Accra
1        Greater Accra
2              Ashanti
3              Ashanti
5              Ashanti
             ...
13956          Western
13957          Western
13958          Eastern
13959          Eastern
13960          Eastern
Name: Region, Length: 13955, dtype: object

### Dropping columns

In [79]:
agric_data.columns

Index(['Record_ID', 'Date', 'Region', 'Crop', 'new_column', 'Rainfall_mm',
       'Yield_kg', 'Price_GHS', 'Temperature_C', 'Farmer_Count', 'Nationality',
       'Revenue', 'Rainfall_group'],
      dtype='object')

In [80]:
### we want to drop the new_column and nationality
### Python will move from one column to the other horizontally, hence we set axis = 1

agric_data.drop(["new_column","Nationality"],axis=1,inplace=True)

In [81]:
agric_data.columns

Index(['Record_ID', 'Date', 'Region', 'Crop', 'Rainfall_mm', 'Yield_kg',
       'Price_GHS', 'Temperature_C', 'Farmer_Count', 'Revenue',
       'Rainfall_group'],
      dtype='object')

In [82]:
agric_data.drop(["Rainfall_group"],axis=1,inplace=True)

In [83]:
agric_data.columns

Index(['Record_ID', 'Date', 'Region', 'Crop', 'Rainfall_mm', 'Yield_kg',
       'Price_GHS', 'Temperature_C', 'Farmer_Count', 'Revenue'],
      dtype='object')

In [84]:
#### removing from row
agric_copy= agric_data.copy()

In [85]:
agric_copy.drop(index=1,axis=0).head(3)
## from the row ,the second row "1" is no longer in the data
### Python move vertically to access the index of each row, hence we set axis to 0

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Revenue
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149,2119.4328
2,3,2021-01-01,Ashanti,Maize,0.00,1467.28,1.92,26.9,320,2817.1776
3,4,2021-01-01,Ashanti,Cassava,10.39,10511.46,1.11,24.5,356,11667.7206

In [86]:
agric_data.shape

(13955, 10)

In [87]:
### checking for missing value
agric_data.isna().sum().sum()

np.int64(0)

In [88]:
agric_data.head(2)

,Record_ID,Date,Region,Crop,Rainfall_mm,Yield_kg,Price_GHS,Temperature_C,Farmer_Count,Revenue
0,1,2021-01-01,Greater Accra,Maize,7.27,1139.48,1.86,32.7,149,2119.4328
1,2,2021-01-01,Greater Accra,Cocoa,4.88,0.00,13.02,24.0,493,0.0000

### Changing  datatypes

In [89]:
agric_data.dtypes

Record_ID          int64
Date              object
Region            object
Crop              object
Rainfall_mm      float64
Yield_kg         float64
Price_GHS        float64
Temperature_C    float64
Farmer_Count       int64
Revenue          float64
dtype: object

In [90]:
agric_data["Date"]

0        2021-01-01
1        2021-01-01
2        2021-01-01
3        2021-01-01
5        2021-01-01
            ...
13956    2023-12-31
13957    2023-12-31
13958    2023-12-31
13959    2023-12-31
13960    2023-12-31
Name: Date, Length: 13955, dtype: object

In [91]:
### Change the date column to a date data type
agric_data["Date"] = pd.to_datetime(agric_data["Date"], format = "%Y-%m-%d", errors = "coerce")

In [92]:
agric_data.dtypes

Record_ID                 int64
Date             datetime64[ns]
Region                   object
Crop                     object
Rainfall_mm             float64
Yield_kg                float64
Price_GHS               float64
Temperature_C           float64
Farmer_Count              int64
Revenue                 float64
dtype: object

In [93]:
### change from object to integer
###agric_data["Record_ID"].astype(float)
###agric_data["Record"].astype("Int64")

### Saving Table

In [94]:
### save the cleaned data to your directory
agric_data.to_csv("Cleaned_agric_data.csv",index=False)

In [95]:
### sum,max, min,mean, median
### Total revenue
print(f"Total revenue is,{agric_data["Revenue"].sum():.2f}")

Total revenue is,9710373.18

In [96]:
print(f"Minimum amount of rainfall,{agric_data["Rainfall_mm"].min():.2f}")

Minimum amount of rainfall,0.00

### Group by
### single colum

In [97]:
### we want to know how much revenue each crop is generating
agric_data.groupby("Crop")["Revenue"].agg("sum")

Crop
Cassava    5.636153e+06
Cocoa      1.947079e+06
Maize      2.127141e+06
Name: Revenue, dtype: float64

In [98]:
### We want to know how much revenue each crop generated by each crop
agric_data.groupby("Crop")["Revenue"].agg(["sum","min"])

                  sum  min
Crop
Cassava  5.636153e+06  0.0
Cocoa    1.947079e+06  0.0
Maize    2.127141e+06  0.0

In [99]:
### We want to know how much revenue each crop generated and know the least revenue generated by each crop
agric_data.groupby("Crop")["Revenue"].agg(["sum","min","max","mean"])

                  sum  min         max         mean
Crop
Cassava  5.636153e+06  0.0  25939.5192  1206.110151
Cocoa    1.947079e+06  0.0   8111.1960   419.991258
Maize    2.127141e+06  0.0   8687.8544   457.843516

In [100]:
## Group by multiple columns
agric_data.groupby("Region")

### Multiple Columns

In [ ]:
### Determine the yield and revenue from each region with respect to each crop
region_Crop_Yield =agric_data.groupby(["Region","Crop"])["Yield_kg"].sum()

In [ ]:
region_Crop_Yield.shape
### (15,) means it is one dimensional

(15,)

In [106]:
region_Crop_Yield.unstack()

Crop              Cassava     Cocoa      Maize
Region
Ashanti        1175655.25  31645.34  223173.78
Eastern         960387.35  31432.16  178660.56
Greater Accra   795644.58  29079.74  153171.53
Northern        834070.52  27907.18  132244.46
Western        1167292.45  43721.89  200679.28

In [102]:
agric_data.columns

Index(['Record_ID', 'Date', 'Region', 'Crop', 'Rainfall_mm', 'Yield_kg',
       'Price_GHS', 'Temperature_C', 'Farmer_Count', 'Revenue'],
      dtype='object')

### Multiple categorical and numeric columns

In [107]:
### Determine the yield and revenue from each region with respect to each crop. Aggregations are sum, mean, and max
agric_multiple =agric_data.groupby(["Region", "Crop"]).agg({"Yield_kg":["sum","mean","max"], "Revenue":["sum", "mean", "max"]}).T
### The "T" means Transpose to change how the Table appeared

In [ ]:
#### to the keys and items in the data
agric_multiple.columns.values

array([('Ashanti', 'Cassava'), ('Ashanti', 'Cocoa'), ('Ashanti', 'Maize'),
       ('Eastern', 'Cassava'), ('Eastern', 'Cocoa'), ('Eastern', 'Maize'),
       ('Greater Accra', 'Cassava'), ('Greater Accra', 'Cocoa'),
       ('Greater Accra', 'Maize'), ('Northern', 'Cassava'),
       ('Northern', 'Cocoa'), ('Northern', 'Maize'),
       ('Western', 'Cassava'), ('Western', 'Cocoa'), ('Western', 'Maize')],
      dtype=object)